<?php
/*
 * TeamWork Module
 * @author Anders Hassis
 * @date 2011-12-08
 */
 
class TeamWork {
  
  /*
   * Get statistic for user
   * @author Anders Hassis
   */
  public static function getAdminStats() {
    $query = '
    SELECT 
      node.created,
      node.title,
      users_projects.status_date,
      users_projects.status_date-node.created as timespent
    FROM 
      node, 
      users_projects
    WHERE 
      users_projects.node_id = node.nid';
    $record = db_query($query);
    
    // Init variables
    $stats = array();
    $stats['avg'] = 0;
    $stats['total'] = 0;
    
    foreach ($record as $rec) { 
      $stats['avg'] += $rec->timespent;
      $stats['total']++;
    }
    
    $total_average = $stats['avg'] / $stats['total'];
    ?>
    Time in average spent on projects before it's marked as completed: <br />
    <strong><?php echo floor($total_average / 3600); ?> hours</strong><br />
    <strong><?php echo floor($total_average / (3600*24)); ?> days</strong>
  
    <?php
  }
  
  /*
   * Get a users applications
   * @author Anders Hassis
   */
  public static function getUserApplications() {
    global $user;

    //SQL query to grab needed infomation from the database
    $query = '
    SELECT 
      node.title, 
      node.nid, 
      webform_submissions.submitted,
      webform_submissions.sid
    FROM 
      node, 
      webform_submissions, 
      webform_submitted_data 
    WHERE 
      webform_submissions.uid = :uid AND 
      webform_submissions.sid = webform_submitted_data.sid AND 
      webform_submitted_data.cid=4 AND 
      webform_submitted_data.data = node.nid AND 
      node.status = 1 
    GROUP BY  
      webform_submissions.uid, 
      webform_submitted_data.data';

    $record = db_query($query, array(':uid' => $user->uid));
    ?>
    <table>
      <thead>
        <td>Date</td>
        <td>Job applied to</td>
        <td>&nbsp;</td>
      </thead>
      
    <?php foreach ($record as $rec) { 
      if (teamwork_job_taken_by_user($rec->nid, $user->uid))
        continue;
      ?>
      <tr>
        <td><?php echo format_date($rec->submitted, 'small'); ?></td>
        <td><a href="./?q=node/<?php echo $rec->nid; ?>"><?php echo $rec->title; ?></a></td>
        <td><a href="/node/20/submission/<?php echo $rec->sid; ?>/delete?destination=my-applications">Delete</a></td>
        </tr>
    <?php
    }
    echo '</table>';
  }
  
  /*
   * Get applicants for a client
   * @author Anders Hassis
   */
  public static function getClientApplications() {
    global $base_url, $user;

    //SQL query to grab needed infomation from the database
    $query = 'SELECT field_data_field_firstname.field_firstname_value as firstname, field_data_field_lastname.field_lastname_value as lastname, webform_submissions.uid as submitter_uid, users.name as name, node.title as title, webform_submitted_data.data as data, webform_submissions.submitted as submit_time FROM webform_submissions, webform_submitted_data, field_data_field_firstname, field_data_field_lastname, users, node, profile WHERE node.uid = :uid AND webform_submissions.sid = webform_submitted_data.sid
    AND webform_submitted_data.cid = :cid AND webform_submissions.uid = users.uid AND webform_submitted_data.data = node.nid AND webform_submissions.uid=profile.uid AND profile.type = :type AND profile.pid = field_data_field_firstname.entity_id AND profile.pid = field_data_field_lastname.entity_id GROUP BY submitter_uid, data';

    $record = db_query($query, array(':cid' => '4', ':uid' => $user->uid, ':type' => 'associate'));
    ?>
    <table>
      <thead>
        <td>Applicant</td>
        <td>Resume</td>
        <td>Job applied to</td>
        <td>Date</td>
      </thead>
      
    <?php foreach ($record as $rec) { 
      if (teamwork_job_taken($rec->data))
        continue;
      ?>
      <tr>
        <td><a href="./?q=profile-associate/<?php echo $rec->submitter_uid; ?>"><?php echo $rec->firstname . ' ' . $rec->lastname; ?></a> </td>
        <td><a href="../employer-resume-view/<?php echo $rec->submitter_uid; ?>">View</a></td>
        <td><a href="./?q=node/<?php echo $rec->data; ?>"><?php echo $rec->title; ?></a></td>
        <td><?php echo format_date($rec->submit_time, 'small'); ?></td>
        <td><a href="<?php echo $base_url; ?>/teamwork/delegate/<?php echo $rec->submitter_uid; ?>/<?php echo $rec->data; ?>">Assign project</a></td>
      </tr>
    <?php
    }
    echo '</table>';
  }
  
  /*
   * Get pending projects for admin
   * @author Anders Hassis
   */
  public static function getPendingProjects() {
    global $base_url, $user;

    //SQL query to grab needed infomation from the database
    $query = '
    SELECT 
      users.name,
      users.uid,
      node.created,
      node.title,
      node.nid
    FROM
      users,
      node
    WHERE
      type = :type AND
      node.uid = users.uid AND
      node.status = 0
    ';
    $record = db_query($query, array(':type' => 'project_template'));
    ?>
    List of projects that hasnt been approved yet.
    <table>
      <thead>
        <td>Job</td>
        <td>User</td>
        <td>Created</td>
        <td>&nbsp;</td>
      </thead>
      
    <?php foreach ($record as $rec) { 
      ?>
      <tr>
        <td><a href="./?q=node/<?php echo $rec->nid; ?>"><?php echo $rec->title; ?></a></td>
        <td><a href="./?q=profile-client/<?php echo $rec->uid; ?>"><?php echo $rec->name; ?></a> </td>
        <td><?php echo format_date($rec->created, 'small'); ?></td>
        <td><a href="<?php echo $base_url; ?>/teamwork/approve_project/<?php echo $rec->nid; ?>">Approve Project</a></td>
      </tr>
    <?php
    }
    echo '</table>';
  }
  
  /*
   * Get pending users for admin
   * @author Anders Hassis
   */
  public static function getPendingUsers() {
    global $base_url, $user;

    //SQL query to grab needed infomation from the database
    $query = '
    SELECT 
      users.name,
      users.uid
    FROM
      users
    WHERE
      users.status = 0
    ';
    $record = db_query($query);
    ?>
    List of users that hasnt been approved yet.
    <table>
      <thead>
        <td>User</td>
        <td>&nbsp;</td>
      </thead>
      
    <?php foreach ($record as $rec) { 
      ?>
      <tr>
        <td><a href="./?q=profile-client/<?php echo $rec->uid; ?>"><?php echo $rec->name; ?></a> </td>
        <td><a href="<?php echo $base_url; ?>/teamwork/approve_user/<?php echo $rec->uid; ?>">Approve User</a></td>
      </tr>
    <?php
    }
    echo '</table>';
  }
  
  /*
   * Get ongoing projects for a client
   * @author Anders Hassis
   */
  public static function getClientOngoingProjects() {
    global $base_url, $user;

    //SQL query to grab needed infomation from the database
    $query = '
    SELECT 
      users.name,
      users.uid,
      node.title,
      node.nid,
      users_projects.id
    FROM
      users_projects,
      users,
      node
    WHERE
      users_projects.user_id = users.uid AND
      users_projects.node_id = node.nid AND
      node.uid = :uid AND
      users_projects.status = 0
    ';
    $record = db_query($query, array(':uid' => $user->uid));
    ?>
    <table>
      <thead>
        <td>Applicant</td>
        <td>Job applied to</td>
        <td>&nbsp;</td>
      </thead>

    <?php foreach ($record as $rec) { 
      ?>
      <tr>
        <td><a href="./?q=profile-associate/<?php echo $rec->uid; ?>"><?php echo $rec->name; ?></a> </td>
        <td><a href="./?q=node/<?php echo $rec->nid; ?>"><?php echo $rec->title; ?></a></td>
        <td><a href="<?php echo $base_url; ?>/teamwork/mark/<?php echo $rec->id; ?>">Mark project as finished</a></td>
      </tr>
    <?php
    }
    echo '</table>';
  }

  /*
   * Get completed projects for a client
   * @author Anders Hassis, Phoeun Phan
   */
  public static function getClientCompletedProjects() {
    global $base_url, $user;

    //SQL query to grab needed infomation from the database
    $query = '
    SELECT 
      users.name,
      users.uid,
      node.title,
      node.nid,
      users_projects.id
    FROM
      users_projects,
      users,
      node
    WHERE
      users_projects.user_id = users.uid AND
      users_projects.node_id = node.nid AND
      node.uid = :uid AND
      users_projects.status = 1
    ';
    $record = db_query($query, array(':uid' => $user->uid));
    ?>
    <table>
      <thead>
        <td>Applicant</td>
        <td>Job applied to</td>
        <td>PERFORMANCE</td>
        <td>COMMUNICATION</td>
        <td>PUNCTUALITY</td>
        <td>ORGANIZATION</td>	
      </thead>

    <?php foreach ($record as $rec) { 
      ?>
      <tr>
        <td><a href="./?q=profile-associate/<?php echo $rec->uid; ?>"><?php echo $rec->name; ?></a> </td>
        <td><a href="./?q=node/<?php echo $rec->nid; ?>"><?php echo $rec->title; ?></a></td>
        <td><?php teamwork_print_rating_stars('profile2', $rec->id, 'performance'); ?></td>
        <td><?php teamwork_print_rating_stars('profile2', $rec->id, 'communication'); ?></td>
        <td><?php teamwork_print_rating_stars('profile2', $rec->id, 'punctuality'); ?></td>
        <td><?php teamwork_print_rating_stars('profile2', $rec->id, 'organization'); ?></td>
      </tr>
    <?php
    }
    echo '</table>';
  }

  /*
   * Block controlling the apply-button for projects
   * @author Anders Hassis
   */
  public static function replyToProject() {
    // Get current user data
    global $user;
    global $node;

    $firstname = "";
    $lastname = "";
    $userID = $user->uid;
    $projectID = arg(1);

    $query = 'SELECT * FROM {profile} LEFT OUTER JOIN {field_data_field_firstname} ON profile.pid = field_data_field_firstname.entity_id LEFT OUTER JOIN {field_data_field_lastname} ON profile.pid = field_data_field_lastname.entity_id WHERE profile.uid = :uid AND profile.type = :type';

    $app_name = db_query($query, array(':uid'=> $user->uid, ':type'=> 'associate'));
    foreach($app_name as $names)
    {
        $firstname = $names->field_firstname_value;
        $lastname = $names->field_lastname_value;
    }

    //echo $firstname . ',' . $lastname . ',' . $userID . ',' . $projectID;
    
    if ( !teamwork_job_taken_by_user($projectID, $userID) ) : ?>
      <form action=".?q=node/20" method="post">
      <input type="hidden" name="appID" value="<?php echo $userID; ?>">
      <input type="hidden" name="firstname" value="<?php echo $firstname; ?>">
      <input type="hidden" name="lastname" value="<?php echo $lastname; ?>">
      <input type="hidden" name="projectID" value="<?php echo $projectID ?>">
      <input type="submit" value="Apply Now">
      </form>
      <?php
    endif;
  }
  
  /*
   * Get projects assigned to a user
   * @author Anders Hassis
   */
  public static function userProjects() {
    global $base_url, $user;
    
    //SQL query to grab needed infomation from the database
    $query = '
    SELECT 
      node.title, 
      node.nid as id,
      users.name
    FROM
      node,
      users,
      users_projects
    WHERE
      node.nid = users_projects.node_id AND
      users_projects.user_id = :uid AND
      node.uid = users.uid
      ';
    $record = db_query($query, array(':uid' => $user->uid ));
    ?>
    <table>
      <thead>
        <td>Client</td>
        <td>Job title</td>
      </thead>
      
    <?php foreach ($record as $rec) : ?>
      <tr>
        <td><?php echo $rec->name; ?></td>
        <td><a href="<?php echo $base_url; ?>/node/<?php $rec->id; ?>"><?php echo $rec->title; ?></a></td>
      </tr>
    <?php
    endforeach;
    echo '</table>';
  }
}

/*
 * Helper function for determining if a project is taken or not
 * @author Anders Hassis
 */
function teamwork_job_taken($node_id) {
  $exists = db_query('SELECT 1 FROM users_projects WHERE node_id = :nid', array(':nid' => $node_id) )->fetchField();

  if ($exists == 1)
    return true;
  else
    return false;
}

/*
 * Helper function for determining if a project is taken or 
 * not by a specified user
 * @author Anders Hassis
 */
function teamwork_job_taken_by_user($node_id, $user_id) {
  $exists = db_query('SELECT 1 FROM users_projects WHERE node_id = :nid AND user_id = :uid', array(':nid' => $node_id, ':uid' => $user_id) )->fetchField();

  if ($exists == 1)
    return true;
  else
    return false;
}

/*
 * Delegate a job to a user
 * @author Anders Hassis
 */
function teamwork_delegate_job($user_id = 0, $node_id = 0) {
  global $base_url;
  
  if ($user_id == 0 || $node_id == 0)
    die("Not enough arguments");
    
  if (teamwork_job_taken($node_id)) {
    die("Project already assigned");
  }
    
  $nid = db_insert('users_projects') // Table name no longer needs {}
  ->fields(array(
    'user_id' => $user_id,
    'node_id' => $node_id
  ))
  ->execute();

  header("location: ". $_SERVER['HTTP_REFERER']);
  die();
}

/*
 * Mark a project as completed
 * @author Anders Hassis
 */
function teamwork_mark($id) {
  global $base_url;
  
  if ($id == 0)
    die("Not enough arguments");
    
  $num_updated = db_update('users_projects') // Table name no longer needs {}
    ->fields(array(
      'status' => 1,
      'status_date' => time()
    ))
    ->condition('id', $id)
    ->execute();

  header("location: ". $_SERVER['HTTP_REFERER']);
  die();
}

/*
 * Approve a project making it visible
 * @author Anders Hassis
 */
function teamwork_approve_project($node_id) {
  global $base_url;
  
  if ($node_id == 0)
    die("Not enough arguments");
    
  $node = node_load($node_id);
  $node->status = 1;
  node_save($node);
  
  header("location: ". $_SERVER['HTTP_REFERER']);
  die();
}

/*
 * Approve a user awaiting reviewal
 * @author Anders Hassis
 */
function teamwork_approve_user($user_id) {
  global $base_url;
  
  if ($user_id == 0)
    die("Not enough arguments");
    
  $num_updated = db_update('users') // Table name no longer needs {}
    ->fields(array(
      'status' => 1,
    ))
    ->condition('uid', $user_id)
    ->execute();

  header("location: ". $_SERVER['HTTP_REFERER']);
  die();
}

/*
 * Show ratings on profile page
 * @author Phoeun Phan
 */
function teamwork_profile_ratings($userid) {
  global $base_url;
  $img = $base_url . '/' . drupal_get_path('module', 'teamwork') . '/stars-';

  // Get votes
  $votes = teamwork_get_votes($userid);
  $labels = array('performance', 'communication', 'punctuality', 'organization');
  
  echo '<table><thead><td><b>PERFORMANCE</b></td><td><b>COMMUNICATION</b></td>';
  echo '<td><b>PUNCTUALITY</b></td><td><b>ORGANIZATION</b></td></thead><thead>';

  foreach($labels as $label){
    teamwork_print_stars($votes[$label]['average'], $votes[$label]['count'], $img, true);
  }

  echo '</thead></table>';
} 

/*
 * Display fixed star ratings
 * @author Phoeun Phan
 */
function teamwork_print_stars($average, $count, $img, $showAvg = false) {
  $avg = $average/20;
  $stars = floor($avg);
  echo '<td><img src="' . $img . $stars .'.gif"/>';
  if ($showAvg) {
    echo '<br>Average: ' . round($avg,2) . ' (' . $count. ' vote';
    echo $count == 1 ? ')' : 's)';
  }
  echo '</td>';
}

/*
 * Display star ratings
 * @author Phoeun Phan
 */
function teamwork_print_rating_stars($entity_type, $entity_id, $tag) {
  $votes = fivestar_get_votes($entity_type, $entity_id, $tag);
  $settings = array(
    'content_type' => $entity_type,
    'content_id' => $entity_id,
    'stars' => 5,
    'autosubmit' => TRUE,
    'allow_clear' => FALSE,
    'text' => 'none',
    'tag' => $tag,
    'style' => 'user',
  );
  print render(drupal_get_form('fivestar_custom_widget', $votes, $settings));
}

/*
 * Show history content on history tab
 * @author Phoeun Phan
 */
function teamwork_profile_history($userid) {
  global $base_url;
  $img = $base_url . '/' . drupal_get_path('module', 'teamwork') . '/stars-';
  $labels = array('performance', 'communication', 'punctuality', 'organization');
  $rating = array(
    'performance' => 0,
    'communication' => 0,
    'punctuality' => 0,
    'organization' => 0);
  
  //SQL query to grab needed infomation from the database
  $query = '
  SELECT 
    users.name,
    users.uid,
    node.title,
    node.nid,
    users_projects.id
  FROM
    users_projects,
    users,
    node
  WHERE
    users_projects.user_id = users.uid AND
    users_projects.node_id = node.nid AND
    users_projects.user_id = :uid AND
    users_projects.status = 1
  ';
  $record = db_query($query, array(':uid' => $userid));
  ?>
  <table>
    <thead>
      <td>Project Completed</td>
      <td>PERFORMANCE</td>
      <td>COMMUNICATION</td>
      <td>PUNCTUALITY</td>
      <td>ORGANIZATION</td>	
    </thead>

  <?php foreach ($record as $rec) { 
      foreach ($labels as $label) {
        $votes = fivestar_get_votes('profile2', $rec->id, $label);
        $rating[$label] = isset($votes['average']['value']) ? $votes['average']['value'] : 0;
      }
    ?>
    <tr>
      <td><a href="./?q=node/<?php echo $rec->nid; ?>"><?php echo $rec->title; ?></a></td>
      <?php
        foreach ($labels as $label) {
          teamwork_print_stars($rating[$label], 1, $img);
        }
      ?>
    </tr>
  <?php
  }
  echo '</table>';
}

/*
 * Get votes for a user
 * @author Phoeun Phan
 */
function teamwork_get_votes($userid) {
  $result = db_query('SELECT id FROM users_projects WHERE user_id = :uid', array(':uid' => $userid));
  $labels = array('performance', 'communication', 'punctuality', 'organization');
  $rating = array(
    'performance' => array(
      'average' => 0,
      'count' => 0,
    ),
    'communication' => array(
      'average' => 0,
      'count' => 0,
    ),
    'punctuality' => array(
      'average' => 0,
      'count' => 0,
    ),
    'organization' => array(
      'average' => 0,
      'count' => 0,
    ),
  );
  foreach($result as $res) {
    foreach($labels as $label) {
      $votes = fivestar_get_votes('profile2', $res->id, $label);
      if (isset($votes['average']['value'])) {
        $rating[$label]['average'] += $votes['average']['value'];
        $rating[$label]['count']++;
      }
    }
  }
  // set average ratings
  foreach($labels as $label) {
    if ($rating[$label]['count'] > 0) {
      $rating[$label]['average'] = round($rating[$label]['average']/$rating[$label]['count'],2);
    }
  }
  return $rating;
}

/*
 * Register routes for internal usage
 * @author Anders Hassis
 */
function teamwork_menu() {
  $items['teamwork/delegate'] = array(
    'page callback' => 'teamwork_delegate_job',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  
  $items['teamwork/mark'] = array(
    'page callback' => 'teamwork_mark',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  
  $items['teamwork/approve_project'] = array(
    'page callback' => 'teamwork_approve_project',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  
  $items['teamwork/approve_user'] = array(
    'page callback' => 'teamwork_approve_user',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK
  );
  
  $items['profile-associate/%user/project-history'] = array(
    'access arguments'  => array('access content'),
    'description'       => "View a specific user's history.",
    'file'              => 'teamwork_project_history.pages.inc',
    'page callback'     => 'history_user_page',
    'page arguments'    => array(1),
    'title'             => 'Project history',
    'type'              => MENU_LOCAL_TASK,
  );
  
  return $items;
}
